### ISSUE TITLE
Main screen window without anything loading

### ISSUE THREAD

**Issue by rickylars** [tomlandia/fuckr#15]
When I launch the software (tried windows 32 and 64 bit) I get the main screen windows without the possibility to press on the buttons or without anything loading.
Reported that before, got an answer it's a bug that was fixed, but that still happens.
I have windows 7. do I need to install the nod webkit to run that?
![image](https://cloud.githubusercontent.com/assets/16501790/12451319/5e27b398-bf91-11e5-8d67-ebb6c7c49c11.png)

**Comment by tomlandia** [comment]
Node-Webkit is packaged in the release. I've just released v1.5 which I've tested on Windows 7 and Vista 32 bits.

**Comment by rickylars** [comment]
Redownloaded from here http://fuckr.me/downloads/Fuckr-win32.zip
get the same problem. Any idea?

**Comment by Kav28** [comment]
Had this happen for several hours last night but no problems this morning.
During the time of the problem the app on my iPad seemed to operate
normally.

During the time of the prob it seemed that moving to another window or
mouse movement would cause the main screen to appear (from a pure white
screen). Could be that the grindr servers were being maintained or under
some circumstances a buffer wasnt being dumped until there was an app
switch. When I signed out of fuckr the screen would be non-responsive and I
had to kill the window/restart. On restart I was prompted for a login and
the location change I did before signing out was reflected in the app.
Looks like under some non-standard circumstances the screen isnt getting
updated.

**Comment by austxtom** [comment]
./Fuckr 
[2754:0220/151742:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[2754:0220/151743:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR
[2754:0220/151743:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR


Ubuntu 14.04, was running fine until I upgraded to the new version.

**Comment by matbonucci** [comment]
Same on Lubuntu 14.04

**Comment by jwax33** [comment]
Encountering the same problem now on Ubuntu 14.04 after upgrading.  If I click the Browse view button I'll get a profile panel full of variable names where data would normally appear.  Does not appear to be connecting to Grindr servers or retrieving any information.

**Comment by tomlandia** [comment]
Apparently adding the --disable-setuid-sandbox Chrome flag in package.json should fix the *Ubuntu update issue but I have no easy way to check

**Comment by jwax33** [comment]
Adding that flag to the package.jason file does resolve the setuid error, but these errors still remain:

[10405:0228/131827:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR
[10405:0228/131829:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR

And appear to prevent Fuckr from communication with the Grindr servers.  The application window opens but it does not logon or retrieve any info.  If you click the grid icon, you get a blank grid screen with $variable_names in the profile pane section.

I can't find any information on what this error actually means via Google, unfortunately.

**Comment by tomlandia** [comment]
I googled/DDG'd with quotes and nobody seems to have a clue besides downgrading NSS... The other obvious solution is too use HTTP 🙊. I'd like to try tweaking SSL/TLS versions (https://productforums.google.com/forum/#!topic/chrome/mE-KUuYBkSU) but I'm having such a hard time using *Ubuntu 14.04 on my Macbook! (VirtualBox doesn't support PAE for live CD's and I can't get Live USB working)

**Comment by tomlandia** [comment]
So @jwax33, I tried on an up-to-date Xubuntu 14.04 32bit VM and Fuckr worked fine with nw 0.12.3 (Fuckr currently uses 0.12.1). Any other clue? Can you update again and try `npm install -g nw` and run it on `fuckr/fuckr`? Thanks a lot!

**Comment by tomlandia** [comment]
Worked with `nw@0.12.1` too :/

**Comment by jwax33** [comment]
When I try the npm install command I get this error output.  Not sure
exactly what it means, will delve into it more when I get over this cold.
Glad to hear Fuckr is working in a clean Xubuntu copy anyway!  And thanks
for the text selection/export fix!

npm http GET https://registry.npmjs.org/nw

npm ERR! Error: failed to fetch from registry: nw
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb
(/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback
(/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous>
(/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach
/home/zone/Documents/F150/Fuckr-linux6415/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.2.0-99-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "nw"
npm ERR! cwd /home/zone/Documents/F150/Fuckr-linux6415
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: nw
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/zone/Documents/F150/Fuckr-linux6415/npm-debug.log
npm not ok

**Comment by tomlandia** [comment]
Could you please test [the new release](https://github.com/tomlandia/fuckr/releases/1.6.0)? It's the first using Node-Webkit 0.14.2. Thanks!

**Comment by matbonucci** [comment]
Still with the latest version doesn't work on Ubuntu 14.04

**Comment by matbonucci** [comment]
Guys this is the problem for me! 
Apparently on the site fuckr.me downloads a corrupted or old Fuckr-linux64.zip that is 40 MB instead of the 57 MB. I downloaded the right file over [here](https://github.com/tomlandia/fuckr/releases) and everything is working fine

**Comment by tomlandia** [comment]
The two issues seem unrelated and all dependencies have been updated in [v1.7.0](https://fuckr.me/). Please create a new issue if v1.7.0 fails on any Linux distro.
