### ISSUE TITLE
No world icon in profiles through chat view

### ISSUE THREAD

**Issue by moaa75** [tomlandia/fuckr#9]
Thanks for this great app!
The world icon for user localization is not shown when selecting a profile from chat view

**Comment by tomlandia** [comment]
Fixed the condition to 'is included in nearby profiles' in v1.4.0 (to be released in a few hours).

Fuckr queries nearby profiles from 3 different points because updating location (PUT /location) then querying a single profile doesn't refresh distance fast enough.

**Comment by jwax33** [comment]
Distance is showing but the globe icon (to click to see user's location map) is still not showing up if you arrive at the user's profile by clicking their pic from chat view.

**Comment by victorgrego** [comment]
Maybe tomlandia did not release the features in this last update. The chat timestamp isn't in this release too.

**Comment by jwax33** [comment]
The timestamps are in this release. They are just there as tooltips that appear if you hover over the chat bubble, not out to the side like in the Grindr client.  Also note that timestamps only exist for messages received after you updated to the 1.40 version. Stuff received before still shows nothing.

**Comment by victorgrego** [comment]
well, maybe i have some outdated stuff here then. I ill check that out. Thanks for the info.
